### ISSUE TITLE
Understanding real time and video rendering

### ISSUE THREAD

**Issue by eferreirafilho** [NVIDIA-Omniverse/OmniIsaacGymEnvs#149]
Hi all, since the commit that added "add viewport recording feature", I'm using this to record videos of the training and inference. However, I'm having a hard time understanding the time scales. I have implemented a simulation using the FrankaDeformable as a basis.

In config.yaml, I have:
```

# disables rendering
headless: False
# enables native livestream
enable_livestream: False
# timeout for MT script
mt_timeout: 300

# enables viewport recording
enable_recording: True
# interval between video recordings (in steps)
recording_interval: 5000
# length of the recorded video (in steps)
recording_length: 900
# fps for writing recorded video
recording_fps: 60
# directory to save recordings in
recording_dir: ''
```

in  the cfg/task file, I have:
```
sim:
  dt: 0.0041 #1/240 s #0.0083 # 1/120 s
  use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
  gravity: [0.0, 0.0, -9.81]
  add_ground_plane: True
  add_distant_light: False
  use_fabric: True
  enable_scene_query_support: False
  disable_contact_processing: False
```

When I run inference with headless=False, I can see the viewport with a varying FPS that stays close to 20 fps. 
 
This way I can create 30 seconds videos (attached), but, how they relate to real time?

https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/92797165/53a3e0d3-407e-47c3-87d6-46fe73808903

To test this, I have set an object at 10 meters high, it should take 1.414 seconds to fall to the ground. But in the rendered video, it only drops around the 10-second mark. This isn't right. What I'm missing?

More importantly, how can I render videos that are real time?

Thanks in advance!
